

inhibit_all_warnings!

platform :ios, '8.0'

target 'LTBaseClassDemo' do
  use_frameworks!

pod 'LTCategories'
pod 'YYCategories'
pod 'IQKeyboardManager'
pod 'Reachability'
  # Pods for LTBaseClassDemo

end
